export let data = [{
        league: "QATAR: Stars League",
        date: "2021-12-29",
        teams: "Al Shamal - Al Rayyan SC",
        result: "2-3",
        matches: 10,
        draw: 3,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "INTERNATIONAL: Suzuki Cup, Group Stage",
        date: "2021-12-29",
        teams: "Indonesia - Thailand",
        result: "3-3",
        matches: 6,
        draw: 2,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "ENGLAND: Premier League",
        date: "2021-12-28",
        teams: "Leicester City - Liverpool",
        result: "0-4",
        matches: 9,
        draw: 1,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "PORTUGAL: Liga Portugal",
        date: "2021-12-28",
        teams: "Moreirense - Estoril",
        result: "1-3",
        matches: 11,
        draw: 5,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "ENGLAND: Premier League",
        date: "2021-12-28",
        teams: "Crystal Palace - Norwich City",
        result: "2-1",
        matches: 4,
        draw: 1,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "ENGLAND: Premier League",
        date: "2021-12-28",
        teams: "Watford - West Ham United",
        result: "2-0",
        matches: 9,
        draw: 2,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "PORTUGAL: Liga Portugal",
        date: "2021-12-28",
        teams: "Maritimo - Vizela",
        result: "0-0",
        matches: 12,
        draw: 4,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "PORTUGAL: Liga Portugal",
        date: "2021-12-28",
        teams: "Tondela - Gil Vicente",
        result: "1-2",
        matches: 7,
        draw: 1,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "INDIA: ISL",
        date: "2021-12-28",
        teams: "Hyderabad - Odisha",
        result: "2-2",
        matches: 4,
        draw: 0,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "ENGLAND: Premier League",
        date: "2021-12-28",
        teams: "Newcastle United - Manchester United",
        result: "1-4",
        matches: 8,
        draw: 3,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "BELGIUM: Jupiler Pro League",
        date: "2021-12-27",
        teams: "Charleroi - Oud-Heverlee",
        result: "0-0",
        matches: 13,
        draw: 5,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "BELGIUM: Jupiler Pro League",
        date: "2021-12-27",
        teams: "Mechelen - RFC Seraing",
        result: "1-1",
        matches: 5,
        draw: 0,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "BELGIUM: Jupiler Pro League",
        date: "2021-12-27",
        teams: "Beerschot-Wilrijk - Anderlecht",
        result: "3-3",
        matches: 11,
        draw: 2,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "BELGIUM: Jupiler Pro League",
        date: "2021-12-27",
        teams: "Sint-Truiden - Eupen",
        result: "3-1",
        matches: 10,
        draw: 2,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
    {
        league: "ENGLAND: Championship",
        date: "2021-12-27",
        teams: "QPR - Bournemouth",
        result: "2-1",
        matches: 8,
        draw: 4,
        editabls: ["league", 'date', "teams", "result", "matches", "draw"],
    },
];



//editable-i paha dataic